lines = [
    "{% extends 'base.html' %}",
    "{% block title %}Dashboard{% endblock %}",
    "{% block page_title %}Dashboard - {{ current_month_name }}{% endblock %}",
    "{% block content %}",
    "<div class=\"row g-3 mb-4\">",
    "  <div class=\"col-md-3 col-6\"><div class=\"card p-3 stat-card income\"><div class=\"text-muted small\">Monthly Income</div><div class=\"fs-4 fw-bold text-success\">{{ currency }} {{ monthly_income|floatformat:2 }}</div></div></div>",
    "  <div class=\"col-md-3 col-6\"><div class=\"card p-3 stat-card expense\"><div class=\"text-muted small\">Monthly Expenses</div><div class=\"fs-4 fw-bold text-danger\">{{ currency }} {{ monthly_expenses|floatformat:2 }}</div></div></div>",
    "  <div class=\"col-md-3 col-6\"><div class=\"card p-3 stat-card savings\"><div class=\"text-muted small\">Monthly Savings</div>{% if monthly_savings >= 0 %}<div class=\"fs-4 fw-bold text-primary\">{{ currency }} {{ monthly_savings|floatformat:2 }}</div>{% else %}<div class=\"fs-4 fw-bold text-danger\">{{ currency }} {{ monthly_savings|floatformat:2 }}</div>{% endif %}</div></div>",
    "  <div class=\"col-md-3 col-6\"><div class=\"card p-3 stat-card networth\"><div class=\"text-muted small\">Net Worth</div>{% if net_worth >= 0 %}<div class=\"fs-4 fw-bold text-warning\">{{ currency }} {{ net_worth|floatformat:2 }}</div>{% else %}<div class=\"fs-4 fw-bold text-danger\">{{ currency }} {{ net_worth|floatformat:2 }}</div>{% endif %}</div></div>",
    "</div>",
    "<div class=\"row g-3 mb-4\">",
    "  <div class=\"col-md-5\"><div class=\"card p-4 h-100\"><h6 class=\"fw-bold mb-3\">Expenses by Category</h6>{% if chart_values != '[]' %}<canvas id=\"expenseChart\"></canvas>{% else %}<p class=\"text-muted text-center py-5\">No expenses this month yet.</p>{% endif %}</div></div>",
    "  <div class=\"col-md-7\"><div class=\"card p-4 h-100\"><h6 class=\"fw-bold mb-3\">Income vs Expenses - Last 6 Months</h6><canvas id=\"monthlyChart\"></canvas></div></div>",
    "</div>",
    "<div class=\"row g-3\">",
    "  <div class=\"col-md-5\"><div class=\"card p-4\">",
    "    <div class=\"d-flex justify-content-between align-items-center mb-3\"><h6 class=\"fw-bold mb-0\">Active Budgets</h6><a href=\"{% url 'budget_list' %}\" class=\"text-decoration-none small text-primary\">View all</a></div>",
    "    {% for budget in active_budgets %}",
    "    <div class=\"mb-3\">",
    "      <div class=\"d-flex justify-content-between mb-1\"><span class=\"small fw-semibold\">{% if budget.category %}{{ budget.category.icon }} {{ budget.category.name }}{% else %}Budget{% endif %}</span><small class=\"text-muted\">{{ budget.spent_amount|floatformat:0 }} / {{ budget.amount|floatformat:0 }}</small></div>",
    "      {% if budget.status == 'exceeded' %}<div class=\"progress\"><div class=\"progress-bar bg-danger\" style=\"width:100%\"></div></div>",
    "      {% elif budget.status == 'warning' %}<div class=\"progress\"><div class=\"progress-bar bg-warning\" style=\"width:{{ budget.usage_percentage|floatformat:0 }}%\"></div></div>",
    "      {% else %}<div class=\"progress\"><div class=\"progress-bar bg-success\" style=\"width:{{ budget.usage_percentage|floatformat:0 }}%\"></div></div>{% endif %}",
    "      <small class=\"text-muted\">{{ budget.usage_percentage|floatformat:0 }}% used</small>",
    "    </div>",
    "    {% empty %}",
    "    <div class=\"text-center text-muted py-3\"><p class=\"small\">No active budgets.</p><a href=\"{% url 'budget_create' %}\" class=\"btn btn-sm btn-outline-primary\">Create Budget</a></div>",
    "    {% endfor %}",
    "  </div></div>",
    "  <div class=\"col-md-7\"><div class=\"card p-4\">",
    "    <div class=\"d-flex justify-content-between align-items-center mb-3\"><h6 class=\"fw-bold mb-0\">Recent Transactions</h6><a href=\"{% url 'transaction_list' %}\" class=\"text-decoration-none small text-primary\">View all</a></div>",
    "    {% if recent_transactions %}",
    "    <div class=\"table-responsive\"><table class=\"table table-hover table-sm mb-0\">",
    "      <thead><tr><th>Date</th><th>Description</th><th>Category</th><th class=\"text-end\">Amount</th></tr></thead>",
    "      <tbody>",
    "      {% for t in recent_transactions %}",
    "        <tr>",
    "          <td class=\"text-muted small\">{{ t.date|date:'M d' }}</td>",
    "          <td class=\"small\">{{ t.description|truncatechars:22 }}</td>",
    "          <td>{% if t.category %}<span class=\"badge\" style=\"background:{{ t.category.color }}22;color:{{ t.category.color }}\">{{ t.category.icon }} {{ t.category.name }}</span>{% else %}<span class=\"text-muted\">-</span>{% endif %}</td>",
    "          {% if t.type == 'income' %}<td class=\"text-end fw-bold small text-success\">+{{ t.currency }} {{ t.amount|floatformat:2 }}</td>",
    "          {% elif t.is_refund %}<td class=\"text-end fw-bold small text-success\">+{{ t.currency }} {{ t.amount|floatformat:2 }}</td>",
    "          {% else %}<td class=\"text-end fw-bold small text-danger\">-{{ t.currency }} {{ t.amount|floatformat:2 }}</td>{% endif %}",
    "        </tr>",
    "      {% endfor %}",
    "      </tbody></table></div>",
    "    {% else %}<div class=\"text-center text-muted py-4\"><p class=\"small\">No transactions yet.</p><a href=\"{% url 'transaction_create' %}\" class=\"btn btn-sm btn-primary\">Add First Transaction</a></div>",
    "    {% endif %}",
    "  </div></div>",
    "</div>",
    "{% endblock %}",
    "{% block extra_js %}",
    "<script>",
    "const labels = {{ chart_labels|safe }};",
    "const values = {{ chart_values|safe }};",
    "const colors = {{ chart_colors|safe }};",
    "const monthlyData = {{ monthly_chart_data|safe }};",
    "if (labels.length > 0) { new Chart(document.getElementById('expenseChart'), { type: 'doughnut', data: { labels, datasets: [{ data: values, backgroundColor: colors, borderWidth: 2 }] }, options: { responsive: true, plugins: { legend: { position: 'bottom' } } } }); }",
    "new Chart(document.getElementById('monthlyChart'), { type: 'bar', data: { labels: monthlyData.map(d => d.month), datasets: [{ label: 'Income', data: monthlyData.map(d => d.income), backgroundColor: 'rgba(16,185,129,0.75)', borderRadius: 6 }, { label: 'Expenses', data: monthlyData.map(d => d.expense), backgroundColor: 'rgba(239,68,68,0.75)', borderRadius: 6 }] }, options: { responsive: true, plugins: { legend: { position: 'top' } }, scales: { y: { beginAtZero: true }, x: { grid: { display: false } } } } });",
    "</script>",
    "{% endblock %}",
]
import os
path = os.path.join('templates', 'dashboard', 'dashboard.html')
with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('SUCCESS - written to', path)
